#%RAML 1.0
title: testing-api
description: testing api

/test:
  get:
    responses: 
      200:
        body: 
          application/json:
            example: 
              message: "Hi, you are an authorized user"
